export class Translate {
  public static contactFormMail = 'contact-form.mail';
  public static contactFormName = 'contact-form.name';
  public static contactFormPhone = 'contact-form.phone';
  public static contactFormRequest = 'contact-form.request';
  public static contactFormRGPD = 'contact-form.rgpd';
  public static contactFormWebsite = 'contact-form.website';
  public static contactMe = 'general.contact-me';
  public static english = 'translate-menu.english';
  public static footerAddress = 'footer.address';
  public static footerAddress01 = 'footer.address-01';
  public static footerAddress02 = 'footer.address-02';
  public static footerContactUs = 'footer.contact-us';
  public static footerEmail = 'footer.email';
  public static footerEmailText = 'footer.email-text';
  public static footerFollowUs = 'footer.follow-us';
  public static footerFollowUsSocial = 'footer.follow-us-social';
  public static footerIndependent = 'footer.independent';
  public static footerPhoneSupport = 'footer.phone-support';
  public static footerPortfolio = 'footer.portfolio';
  public static footerPrivacy = 'footer.privacy';
  public static footerQuickLinks = 'footer.quick-links';
  public static footerSchedule = 'footer.schedule';
  public static footerServices = 'footer.services';
  public static footerTerms = 'footer.terms';
  public static french = 'translate-menu.french';
  public static generalMoreDetails = 'general.more-details';
  public static heroContact01 = 'hero.contact-01';
  public static heroContact02 = 'hero.contact-02';
  public static heroh101 = 'hero.h1-01';
  public static heroh102 = 'hero.h1-02';
  public static heroh103 = 'hero.h1-03';
  public static heroh104 = 'hero.h1-04';
  public static heroh105 = 'hero.h1-05';
  public static home = 'general.home';
  public static homeApplication = 'home.application'; // dynamic
  public static homeApplicationText = 'home.application-text'; // dynamic
  public static homeCompletedProjects = 'home.completed-projects';
  public static homeCompleteRange = 'home.complete-range';
  public static homeContactMeProject = 'home.contact-me-project';
  public static homeContactMeProjectText = 'home.contact-me-project-text';
  public static homeExperienceExpertise = 'home.experience-expertise';
  public static homeExperienceExpertiseText = 'home.experience-expertise-text';
  public static homeExpertsPassion01 = 'home.experts-passion-01';
  public static homeExpertsPassion02 = 'home.experts-passion-02';
  public static homeExpertsPassion03 = 'home.experts-passion-03';
  public static homeExpertsPassionText01 = 'home.experts-passion-text-01';
  public static homeExpertsPassionText02 = 'home.experts-passion-text-02';
  public static homeMission01 = 'home.mission-01';
  public static homeMission02 = 'home.mission-02';
  public static homeMissionText = 'home.mission-text';
  public static homePreliminaryStudy = 'home.preliminary-study'; // dynamic
  public static homePreliminaryStudyText = 'home.preliminary-study-text'; // dynamic
  public static homePromotionnalMarketing = 'home.promotionnal-marketing'; // dynamic
  public static homePromotionnalMarketingText = 'home.promotionnal-marketing-text'; // dynamic
  public static homeRecommendations = 'home.recommendations'; // dynamic
  public static homeRecommendationsText = 'home.recommendations-text'; // dynamic
  public static homeRedesignWebsite = 'home.redesign-website'; // dynamic
  public static homeRedesignWebsiteText = 'home.redesign-website-text'; // dynamic
  public static homeSatisfiedCompanies = 'home.satisfied-companies';
  public static homeSatisfiedCustomers = 'home.satisfied-customers';
  public static homeSeePorfolio = 'home.see-porfolio';
  public static homeServicesPremium01 = 'home.services-premium-01';
  public static homeServicesPremium02 = 'home.services-premium-02';
  public static homeServicesPremium03 = 'home.services-premium-03';
  public static homeSYearsExperience = 'home.years-experience';
  public static homeTransformReality = 'home.transform-reality';
  public static homeTurnOnVision = 'home.turn-on-vision';
  public static homeTurnOnVisionText = 'home.turn-on-vision-text';
  public static homeVisionOcean = 'home.vision-ocean';
  public static homeWebsiteCreation = 'home.website-creation'; // dynamic
  public static homeWebsiteCreationText = 'home.website-creation-text'; // dynamic
  public static navbarAskQuote = 'navbar.ask-quote';
  public static navbarContact = 'navbar.contact';
  public static navbarCreateWebsite = 'navbar.create-website';
  public static navbarProjects = 'navbar.projects';
  public static navbarPromotionalMarketing = 'navbar.promotional-marketing';
  public static navbarRedisignWebsite = 'navbar.redisign-website';
  public static navbarServices = 'navbar.services';
  public static reviewsTrustedUs = 'reviews.trusted-us';
  public static reviewsTrustedUsText = 'reviews.trusted-us-text';
  public static contactInformation = 'contact.get-information';
  public static contactInformationText = 'contact.get-information-text';
  public static contactErrorCheckCase = 'contact-form.error.check-case';
  public static contactErrorEmail = 'contact-form.error.email';
  public static contactErrorEmailPattern = 'contact-form.error.email-pattern';
  public static contactErrorPhone = 'contact-form.error.phone';
  public static contactErrorRequired = 'contact-form.error.required';
  public static reviewsLoading = 'reviews.loading';
  public static contactMoreInfo = 'contact.more-info';
  public static contactMoreInfoText = 'contact.more-info-text';
  public static contactFormSendMessage = 'contact-form.send-message';
  public static contactFormPhoneRGPD = 'contact-form.rgpd-phone';
  public static contactFormSendInProgress = 'contact-form.send-in-progress';
  public static contactFormErrorMessage = 'contact-form.error-message';
  public static contactFormSuccessMessage = 'contact-form.success-message';
  public static contactFormCalledBack = 'contact.need-called-back';
  public static contactFormCalledBackText = 'contact.need-called-backt-text';
  public static contactFormSummary = 'contact.summary';
  public static websiteCreationBenefits01Description = 'services.website-creation.benefits-01-description'; // dynamic
  public static websiteCreationBenefits01Title = 'services.website-creation.benefits-01-title'; // dynamic
  public static websiteCreationBenefits02Description = 'services.website-creation.benefits-02-description'; // dynamic
  public static websiteCreationBenefits02Title = 'services.website-creation.benefits-02-title'; // dynamic
  public static websiteCreationBenefits03Description = 'services.website-creation.benefits-03-description'; // dynamic
  public static websiteCreationBenefits03Title = 'services.website-creation.benefits-03-title'; // dynamic
  public static websiteCreationBenefitsTitle = 'services.website-creation.benefits-title';
  public static websiteCreationCatalogDescription = 'services.website-creation.catalog-description';
  public static websiteCreationCatalogTitle = 'services.website-creation.catalog-title';
  public static websiteCreationTogetherDescription = 'services.website-creation.contact-together-description';
  public static websiteCreationTogetherTitle = 'services.website-creation.contact-together-title';
  public static websiteCreationDevelopActivity = 'services.website-creation.develop-activity';
  public static websiteCreationECommerceDescription = 'services.website-creation.e-commerce-description';
  public static websiteCreationECommerceTitle01 = 'services.website-creation.e-commerce-title-01';
  public static websiteCreationECommerceTitle02 = 'services.website-creation.e-commerce-title-02';
  public static websiteCreationShineDescription = 'services.website-creation.shine-description';
  public static websiteCreationShineTitle = 'services.website-creation.shine-title';
  public static websiteCreationShowcaseDescription = 'services.website-creation.showcase-description';
  public static websiteCreationShowcaseTitle01 = 'services.website-creation.showcase-title-01';
  public static websiteCreationShowcaseTitle02 = 'services.website-creation.showcase-title-02';
  public static websiteCreationShowcaseTitle03 = 'services.website-creation.showcase-title-03';
}
